version: '3.1'

services:
  vizzly:
    image: ghcr.io/vizzly-co/query-engine-private:18d9d5e0d14a8bbf40d473eed1959877946eea9c
    ports:
      - 8000:8000
    volumes:
      - ./datadir:/etc


  customer_postgres_14_2:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_PASSWORD: customer
      POSTGRES_USER: customer
    ports:
      - 6400:5432
    volumes:
      - ./inits/postgres_14_2/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./datasets:/var/lib/postgresql/csvs
